Fixing issues after review p12&14
horodniuk/shopping_cart pull request #26
Opened 2023-01-14 15:34 UTC by vhumenny

fixed issues 12 and 14 in the list, Added classes for each command, also added abstract class Command, added class ParsedCommand, moved the logic of executing commands from method parse() to method executeCommand().

2023-01-14 20:21 UTC, horodniuk requested changes

2023-01-14 20:21 UTC, horodniuk commented on src/main/java/commands/CommandAdd.java
> +    }
Method matches repeated in each command class, can be moove this method in  to class Command

2023-01-14 20:21 UTC, horodniuk commented on src/main/java/commands/CommandAdd.java
> +
Add comment or example for regular expression to make it clear

2023-01-14 20:21 UTC, horodniuk commented on src/main/java/runner/TextModeRunner.java
> +                    cart.applyDiscount(cartCommandParser.parseDiscount(arguments.get(1)), arguments.get(2));
add comment or example arguments.get(1) and arguments.get(2)

2023-01-15 11:45 UTC, vhumenny commented on src/main/java/commands/CommandAdd.java
> +    }
fixed

2023-01-15 11:54 UTC, vhumenny commented on src/main/java/commands/CommandAdd.java
> +
fixed

2023-01-15 12:01 UTC, vhumenny commented on src/main/java/runner/TextModeRunner.java
> +                    cart.applyDiscount(cartCommandParser.parseDiscount(arguments.get(1)), arguments.get(2));
fixed

2023-01-15 12:31 UTC, merged